def format_summary(summary_text: str) -> str:
    # Simple output scaffolding – keep it readable in Discord
    return (
        "**TL;DR (Chat Summary)**\n"
        f"{summary_text}\n\n"
        "_Generated by Summarizer Bot_"
    )
